Modules/Category/Routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::prefix('administrator/category')->name('category.')->group(function() {
    Route::get('/', [\Modules\Category\Http\Livewire\ListCategory::class,'__invoke'])->name('list_category');
    Route::get('/create', [\Modules\Category\Http\Livewire\CreateCategory::class, '__invoke'])->name('create_category');
});

Modules/Category/Http/Controllers/CategoryController.php
<?php

namespace Modules\Category\Http\Controllers;

use App\Models\User;
use Illuminate\Auth\Access\Response;
use Illuminate\Contracts\Support\Renderable;
use Illuminate\Http\Request;
use Illuminate\Routing\Controller;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Gate;

class CategoryController extends Controller
{

    /**
     * Display a listing of the resource.
     * @return Renderable
     */
    public function index()
    {

        return view('category::index');
    }

    /**
     * Show the form for creating a new resource.
     * @return Renderable
     */
    public function create()
    {
        return view('category::create');
    }

    /**
     * Store a newly created resource in storage.
     * @param Request $request
     * @return Renderable
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Show the specified resource.
     * @param int $id
     * @return Renderable
     */
    public function show($id)
    {
        return view('category::show');
    }

    /**
     * Show the form for editing the specified resource.
     * @param int $id
     * @return Renderable
     */
    public function edit($id)
    {
        return view('category::edit');
    }

    /**
     * Update the specified resource in storage.
     * @param Request $request
     * @param int $id
     * @return Renderable
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     * @param int $id
     * @return Renderable
     */
    public function destroy($id)
    {
        //
    }
}

Modules/Category/Http/Livewire/CreateCategory.php
<?php

namespace Modules\Category\Http\Livewire;

use App\Models\Category;
use Livewire\Component;

class CreateCategory extends Component
{
    public $name, $description;
    public $record_id = 0;
    protected $queryString = ['record_id'];

    public function formSubmit(){
        if ($this->record_id > 0) {
            $this->update();
        } else {
            $this->create();
        }
    }
    public function rules()
    {
        return [
            'name' => 'string|required|min:6',
            'description' => 'string|required|min:6',

        ];
    }
    public function updated($propertyName)
    {
        $this->validateOnly($propertyName);
    }
    public function mount(){
        if($this->record_id > 0){
            $dataCate = Category::findOrFail($this->record_id);
            $this->name = $dataCate->name;
            $this->description = $dataCate->description;

        }
    }
    public function update(){
        $this->rules();
        $dataCate = Category::findOrFail($this->record_id);
        if($dataCate){
            $dataCate->fill([
                'name'=>$this->name,
                'description'=>$this->description
            ]);
        }
        if (!$dataCate->clean) {
            $dataCate->update();
            session()->flash('alert-success', 'Cập nhật thành công!');
            return redirect(route('category.list_category'));
        } else {
            return redirect()->back()->with('alert-error', "Cập nhật không thành công!");
        }
    }
    public function create(){
        $this->validate();
        $dataCate = Category::create([
           'name'=>$this->name,
            'description'=>$this->description
        ]);
        session()->flash('alert-success', 'Thêm mới thành công!');
        return redirect()->route('category.list_category');
    }
    public function render()
    {
        return view('category::livewire.create_category')->layout('category::layouts.master');
    }
}

Modules/Category/Http/Livewire/ListCategory.php
<?php

namespace Modules\Category\Http\Livewire;

use Livewire\Component;
use App\Models\Category;


class ListCategory extends Component
{
    public $listCategory;
    public $turnModal = false;
    public $idCate;
    public function turnModal($id){
        $this->turnModal = true;
        $this->idCate = $id;
    }
    public function closeModal(){
        $this->turnModal = false;
    }
    public function acceptDelete(){
    if($this->idCate){
        $data = Category::findOrFail($this->idCate);
        $this->turnModal = false;
        if($data){
            $data->delete();
        }
    }
    return redirect()->back();
}
    public function render()
    {
        $this->listCategory = Category::orderBy('id','desc')->get();
        return view('category::livewire.list_category',['dataCate'=>$this->listCategory])->layout('category::layouts.master');
    }


}

Modules/Category/Resources/views/index.blade.php
@extends('category::layouts.master')

@section('content')
    <h1>Hello World</h1>

    <p>
        This view is loaded from module: {!! config('category.name') !!}
    </p>
@endsection

Modules/Category/Resources/views/layouts/master.blade.php
<x-ladmin-layout>
    <x-slot name="title"></x-slot>
    <link rel="stylesheet" href="{{ asset('css/create-cate.css') }}">
    <link rel="stylesheet" href="{{ asset('css/category.css') }}">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.0/jquery.min.js"></script>
    @livewireStyles

    {{$slot}}
    <script src="{{ asset('js/category.js') }}"></script>
    @livewireScripts
</x-ladmin-layout>

Modules/Category/Resources/views/livewire/create_category.blade.php
{{--@extends('category::layouts.master')--}}
{{--@section('style')--}}
{{--    <link rel="stylesheet" href="{{ asset('css/create-cate.css') }}">--}}
{{--@endsection--}}
{{--@section('content')--}}
<div>
        <x-slot name="title">Create Category</x-slot>
        <div id="create-category">
            <div class="wrap-category">
                <div class="option-category ">
                    <div class="option-1 ">
                    </div>
                </div>
            </div>
            <div class="main-category ">
                @if(session('alert-error'))
                    <div class="bg-red-300 border-t-4 border-red-500 rounded-b text-white px-4 py-3 shadow-md mb-2"
                         role="alert">
                        <div class="flex">
{{--                            <div class="icon-done">{!! showIcon('error') !!}</div>--}}
                            <div>
                                <p class="font-bold pl-1">{{session('alert-error')}}</p>
                            </div>
                        </div>
                    </div>
                @endif
                <div class="main-content">
                    <div class="item-category">
                        <div class="row-attribute row-1">
                            <div class="title">Tên danh mục</div>
                            <div class="input-cate ">
                                <input wire:model="name" type="text" id="name" name="name">
                            </div>
                        </div>
                        <div class="row-attribute">
                            <div class="title">Mô tả</div>
                            <div class="input-cate">
                                <textarea wire:model="description" type="text" id="description" name="description"></textarea>
                            </div>
                        </div>
                        <div class="row-attribute">
                            <button type="submit"  wire:click.prevent="formSubmit" class="btn btn-info">Create</button>
                        </div>
                    </div>
                </div>
            </div>

        </div>

</div>
{{--@endsection--}}

Modules/Category/Resources/views/livewire/list_category.blade.php
{{--@extends('category::layouts.master')--}}
{{--@section('style')--}}
{{--    <link rel="stylesheet" href="{{ asset('css/category.css') }}">--}}
{{--@endsection--}}
{{--@section('content')--}}

<div>
    <x-slot name="buttons">List Category</x-slot>
    <div class="list-category">
        <div class="wrap-category">
            <div class="option-category ">
                <div class="title"><label>Danh sách danh mục</label></div>
                <div class="option-1 ">
                    <a href="{{route('category.create_category')}}" class="create btn btn-primary" title="create">Create</a>
                </div>
            </div>
        </div>
        @if(session('alert-success'))
            <div class="alert-success bg-blue-300 border-t-4 border-blue-500 rounded-b text-white px-4 py-3 shadow-md mb-2"
                 role="alert">
                <div class="flex">
                    <div>
                        <p class="font-bold pl-1">{{session('alert-success')}}</p>
                    </div>
                </div>
            </div>
        @endif
        <div class="main-category ">
            <div class="main-content">
                <div class="list-category">
                    <div class="item-category">
                        <div class="search">
                            <p>Show 10 entries</p>
                        </div>
                        <table class=" table-auto">
                            <thead>
                                <tr>
                                    <th class="">STT</th>
                                    <th class="col-name ">Tên danh mục</th>
                                    <th class="col-des w-1/6 ">Mô tả</th>
                                    <th class="col-option ">Tùy chọn</th>
                                </tr>
                            </thead>
                            <tbody>
                            @foreach($dataCate as $key=>$value)
                                <tr>
                                    <td>{{$loop->index +1}}</td>
                                    <td>{{$value->name}}</td>
                                    <td>{{$value->description}}</td>
                                    <td >
                                        <a href="{{route('category.create_category',['record_id'=>$value->id])}}" class="btn btn-info">Edit</a>
                                        <button type="button"   wire:click="turnModal({{$value->id}})" class="btn btn-primary"
                                                data-toggle="modal" data-target="#exampleModal" >Delete</button>
                                    </td>
                                </tr>
                            @endforeach
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
        @if($turnModal)
        <x-category::category.From.modal wire:model="turnModal"/>
        @endif
    </div>
</div>
<script>
    $('#myModal').on('shown.bs.modal', function () {
        $('#myInput').trigger('focus')
    })
</script>
{{--@endsection--}}