Modules/Product/Routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::prefix('administrator/product')->name('product.')->group(function(){
    Route::get('/', [\Modules\Product\Http\Livewire\ListProduct::class,'__invoke'])->name('list_product');
    Route::get('/create', [\Modules\Product\Http\Livewire\CreateProduct::class,'__invoke'])->name('create_product');
});

Modules/Product/Http/Controllers/ProductController.php
<?php

namespace Modules\Product\Http\Controllers;

use Illuminate\Contracts\Support\Renderable;
use Illuminate\Http\Request;
use Illuminate\Routing\Controller;

class ProductController extends Controller
{
    /**
     * Display a listing of the resource.
     * @return Renderable
     */
    public function index()
    {
        return view('product::index');
    }

    /**
     * Show the form for creating a new resource.
     * @return Renderable
     */
    public function create()
    {
        return view('product::create');
    }

    /**
     * Store a newly created resource in storage.
     * @param Request $request
     * @return Renderable
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Show the specified resource.
     * @param int $id
     * @return Renderable
     */
    public function show($id)
    {
        return view('product::show');
    }

    /**
     * Show the form for editing the specified resource.
     * @param int $id
     * @return Renderable
     */
    public function edit($id)
    {
        return view('product::edit');
    }

    /**
     * Update the specified resource in storage.
     * @param Request $request
     * @param int $id
     * @return Renderable
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     * @param int $id
     * @return Renderable
     */
    public function destroy($id)
    {
        //
    }
}

Modules/Product/Http/Livewire/CreateProduct.php
<?php

namespace Modules\Product\Http\Livewire;

use App\Models\Category;
use App\Models\Product;
use Livewire\Component;

class CreateProduct extends Component
{
    public $name, $sale_price, $market_price, $summary, $category_id, $manufacturer, $description;
    public $dataCate;
    public $record_id = 0;
    protected $queryString = ['record_id'];
    public function updated($propertyName)
    {
        $this->validateOnly($propertyName);
    }
    public function formSubmit(){
        if($this->record_id >0){
            $this->update();
        }else{
            $this->create();
        }
    }
    public function mount(){
        if($this->record_id >0 ){
            $dataProduct = Product::findOrFail($this->record_id);
            if($dataProduct){
                $this->name = $dataProduct->name;
                $this->sale_price = $dataProduct->sale_price;
                $this->market_price = $dataProduct->market_price;
                $this->summary = $dataProduct->summary;
                $this->description = $dataProduct->description;
                $this->manufacturer = $dataProduct->manufacturer;
                $this->category_id = $dataProduct->category_id;
            }
        }
    }
    public function update(){
        $this->rules();
        $dataProduct = Product::findOrFail($this->record_id);
        if($dataProduct){
            $dataProduct->fill([
                'name'=>$this->name,
                'sale_price'=>$this->sale_price,
                'market_price'=>$this->market_price,
                'summary'=>$this->summary,
                'description'=>$this->description,
                'manufacturer'=>$this->manufacturer,
                'category_id'=>$this->category_id
            ]);
        }
        if (!$dataProduct->clean) {
            $dataProduct->update();
            session()->flash('alert-success', 'Cập nhật thành công!');
            return redirect(route('product.list_product'));
        } else {
            return redirect()->back()->with('alert-error', "Cập nhật không thành công!");
        }
    }
    public function rules(){
        return [
            'name' => 'string|required|min:6',
            'description' => 'string|required|min:6',
            'manufacturer' => 'string|required|min:6',
            'sale_price' => 'required',
            'market_price' => 'required',
            'summary' => 'string|required|min:6',
            'category_id' => 'required',
        ];
    }
    public function create(){
        $this->validate();
        $dataProduct = Product::create([
            'name'=>$this->name,
            'sale_price'=>$this->sale_price,
            'market_price'=>$this->market_price,
            'summary'=>$this->summary,
            'description'=>$this->description,
            'manufacturer'=>$this->manufacturer,
            'category_id'=>$this->category_id
        ]);
        session()->flash('alert-success', 'Thêm mới thành công!');
        return redirect()->route('product.list_product');
    }
    public function render()
    {
        $this->dataCate = Category::get();
        return view('product::livewire.create-product')->layout('product::layouts.master');
    }
}

Modules/Product/Http/Livewire/ListProduct.php
<?php

namespace Modules\Product\Http\Livewire;

use App\Models\Product;
use Livewire\Component;

class ListProduct extends Component
{
    public $dataProduct;
    public $idProduct, $turnModal=false;
    public function turnModal($id){
        $this->idProduct = $id;
        $this->turnModal = true;
    }
    public function closeModal(){
        $this->turnModal = false;
    }
    public function acceptDelete(){
        if($this->idProduct){
            $data = Product::findOrFail($this->idProduct);
            $this->turnModal = false;
            if($data){
                $data->delete();
            }
        }
        return redirect()->back();
    }
    public function render()
    {
        $this->dataProduct = Product::get();
        return view('product::livewire.list-product')->layout('product::layouts.master');
    }
}

Modules/Product/Resources/views/index.blade.php
@extends('product::layouts.master')

@section('content')
    <h1>Hello World</h1>

    <p>
        This view is loaded from module: {!! config('product.name') !!}
    </p>
@endsection

Modules/Product/Resources/views/layouts/master.blade.php
<x-ladmin-layout>
    <x-slot name="title"></x-slot>
    <link rel="stylesheet" href="{{ asset('css/product.css') }}">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.0/jquery.min.js"></script>
    @livewireStyles

    {{$slot}}
    <script src="{{ asset('js/product.js') }}"></script>
    @livewireScripts
</x-ladmin-layout>

Modules/Product/Resources/views/livewire/create-product.blade.php
<div>
    <x-slot name="title">Create Category</x-slot>
    <div class="create-product">
        <div class="wrap-product">
            <div class="option-product ">
                <div class="option-1 ">
                </div>
            </div>
        </div>
        <div class="main-product ">
            @if(session('alert-error'))
                <div class="bg-red-300 border-t-4 border-red-500 rounded-b text-white px-4 py-3 shadow-md mb-2"
                     role="alert">
                    <div class="flex">
                        <div>
                            <p class="font-bold pl-1">{{session('alert-error')}}</p>
                        </div>
                    </div>
                </div>
            @endif
            <div class="main-content">
                <div class="item-product">
                    <div class="row-attribute row-1">
                        <div class="title">Tên sản phẩm</div>
                        <div class="input-product ">
                            <input wire:model="name" type="text" id="name" name="name">
                        </div>
                    </div>
                    <div class="row-attribute">
                        <div class="title">Giá sản phẩm</div>
                        <div class="input-product ">
                            <input wire:model="sale_price" type="text" id="sale_price" name="sale_price">
                        </div>
                    </div>
                    <div class="row-attribute">
                        <div class="title">Giá trị trường</div>
                        <div class="input-product ">
                            <input wire:model="market_price" type="text" id="market_price" name="market_price">
                        </div>
                    </div>
                    <div class="row-attribute">
                        <div class="title">Tóm tắt</div>
                        <div class="input-product ">
                            <input wire:model="summary" type="text" id="summary" name="summary">
                        </div>
                    </div>
                    <div class="row-attribute">
                        <div class="title">Nhà sản xuất</div>
                        <div class="input-product ">
                            <input wire:model="manufacturer" type="text" id="manufacturer" name="manufacturer">
                        </div>
                    </div>
                    <div class="row-attribute">
                        <div class="title">Mô tả</div>
                        <div class="input-product">
                            <textarea wire:model="description" type="text" id="description" name="description"></textarea>
                        </div>
                    </div>
                    <div class="row-attribute">
                        <div class="title">Danh mục</div>
                        <div class="input-product">
                            <select wire:model="category_id">
                                <option>---Chọn danh mục</option>
                                @foreach($dataCate as $key=>$value)
                                <option value="{{$value->id}}" id="{{$key}}">{{$value->name}}</option>
                                @endforeach
                            </select>
                        </div>
                    </div>
                    <div class="row-attribute">
                        <button type="submit"  wire:click.prevent="formSubmit" class="btn btn-info">Create</button>
                    </div>
                </div>
            </div>
        </div>

    </div>

</div>

Modules/Product/Resources/views/livewire/list-product.blade.php
<div>
    <x-slot name="buttons">List Product</x-slot>
    <div class="list-product">
        <div class="wrap-product">
            <div class="option-product ">
                <div class="title"><label>Danh sách sản phẩm</label></div>
                <div class="option-1 ">
                    <a href="{{route('product.create_product')}}" class="create btn btn-primary" title="create">Create</a>
                </div>
            </div>
        </div>
        @if(session('alert-success'))
            <div class="alert-success bg-blue-300 border-t-4 border-blue-500 rounded-b text-white px-4 py-3 shadow-md mb-2"
                 role="alert">
                <div class="flex">
                    {{--                    <div class="icon-done">{!! showIcon('done') !!}</div>--}}
                    <div>
                        <p class="font-bold pl-1">{{session('alert-success')}}</p>
                    </div>
                </div>
            </div>
        @endif
        <div class="main-product ">
            <div class="main-content">
                <div class="item-product">
                    <div class="search">
                        <p>Show 10 entries</p>
                    </div>
                    <table class=" table-auto">
                        <thead>
                        <tr>
                            <th class="">STT</th>
                            <th class="col-name ">Tên sản phẩm</th>
                            <th class="col-name ">Tên danh mục</th>
                            <th class="col-name ">Giá sản phẩm</th>
                            <th class="col-name ">Giá thị trường</th>
                            <th class="col-name ">Tóm tắt</th>
                            <th class="col-option ">Tùy chọn</th>
                        </tr>
                        </thead>
                        <tbody>
                        @foreach($dataProduct as $key=>$value)
                            <tr>
                                <td>{{$loop->index +1}}</td>
                                <td>{{$value->name}}</td>
                                <td>{{$value->category->name}}</td>
                                <td>{{$value->sale_price}}</td>
                                <td>{{$value->market_price}}</td>
                                <td>{{$value->summary}}</td>
                                <td >
                                    <a href="{{route('product.create_product',['record_id'=>$value->id])}}" class="btn btn-info">Edit</a>
                                    <button type="button" wire:click.prevent="turnModal({{$value->id}})" class="btn btn-primary"
                                    >Delete</button>
                                </td>
                            </tr>
                        @endforeach
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
        @if($turnModal)
            <x-product::product.Form.modal wire:model="turnModal"/>
        @endif
    </div>
</div>